# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  smoke-test:
    name: "Test"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore NuGet packages
      run: |
        cd Magitek
        nuget restore Magitek.sln
    - name: Build solution
      run: |
        cd Magitek
        msbuild Magitek.sln /p:Configuration=Release
    - name: Generate Version.txt
      run: echo "test-${{ github.run_number }}" > ./Magitek/bin/release/Version.txt

    - name: Create Magitek.zip
      run: |
        powershell Compress-Archive -Path ./Magitek/bin/release/Magitek.dll, ./Magitek/bin/release/Version.txt, ./MagitekLoader/MagitekLoader.cs -DestinationPath ./Magitek/bin/release/Magitek.zip

    - name: Upload Artifacts for Release
      uses: actions/upload-artifact@v2
      with:
        name: Magitek.zip
        path: ./Magitek/bin/release/Magitek.zip

    - name: Upload Version.txt for Release
      uses: actions/upload-artifact@v2
      with:
        name: Version.txt
        path: ./Magitek/bin/release/Version.txt
